oot: true

parserOptions:
  ecmaVersion: latest
  sourceType: module

extends:
  - problems
  - eslint:recommended
  - plugin:import/recommended
  - prettier

plugins:
  - prettier

env:
  node: true

settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .mjs

rules:
  prettier/prettier: error
  no-fallthrough: off
  no-undef-init: off
  no-console: off
  prefer-rest-params: off
  eqeqeq: [2, 'smart']
