version: '3'
services:

  redis:
    image: redis
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/redis.conf
    command: >
      redis-server /redis.conf
