sequenceDiagram

actor client

client->>+doorkeeper: hej doorkeeper, let me in!
Note right of client: POST /session/login<br>login=abc<br>password=xyz

doorkeeper->>+store: are the login credentials valid?
store->>doorkeeper: yes, here is the user info
doorkeeper->>store: please, save the last login time<br>and remember the token (until it expires)

doorkeeper->>-client: okay, here is your login token!
Note left of doorkeeper: 200 OK<br>Content-Type: application/jwt

