sequenceDiagram

autonumber

actor client
participant doorkeeper
participant up as user provider
participant store

client->>+doorkeeper: hej doorkeeper, let me in!
Note right of client: POST /token/login<br>login=abc<br>password=xyz

doorkeeper->>up: are the login credentials valid?
activate up
up-->>doorkeeper: yes, here is the user info
deactivate up

doorkeeper->>store: please, save the login time<br>and remember the token (until it expires)

doorkeeper-->>-client: okay, here is your login token!
Note left of doorkeeper: 200 OK<br>Content-Type: application/jwt

